name: blood_donation
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^11.0.0
  google_maps_flutter: ^2.5.3
  http: ^1.2.0
  url_launcher: ^6.2.6
  google_fonts: ^6.2.0
  #location: ^6.0.1
  
  
 
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  

flutter:
  uses-material-design: true

  assets:
    - images/ill_1.png
    - images/ill_2.png
    - images/ill_3.png
    - images/ill_4.png
    - images/ill_5.png
    - images/ill_6.png
    - images/ill_blood-min.png
    
